---
dependencies: []

  description: NFS installation for Linux.
  company: "Storin"
  min_ansible_version: 2.9.7
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - system
    - nfs
    - filesystem
    - share
    - nfsv4
    - efs
