---
# tasks file for nfs-client-playbook
# Insert the needed variables
  
- name: Install NFS Utilities Software
  yum:
    name: nfs-utils
    state: present
        
- name: Create Mount Point for Client
  file:
    path: "{{nfspath}}"
    state: directory

- name: Mount NFS Share for NFS-SERVER
  mount:
    path: "{{nfspath}}"
    src: "{{nfsmount}}"
    fstype: nfs4
    opts: "{{nfsoptions}}"
    state: mounted

- name: start nfs
  become: yes
  service:
    name: nfs
    state: started
    enabled: yes
  
