---
# vars file for nfs-client-playbook

# This task is used to mount a filesystem via NFS.
# 
# Variables you need to define:
nfsserver:  server
nfspath:  /mnt/test
nfsmount:  172.29.133.107:/home/public 
nfsoptions: ro,bg,hard,nointr,rsize=32768,wsize=32768,tcp,vers=4,timeo=600
#
# Please note that the task will check if the {{nfsmount}} directory
# exists and create it otherwise.
#
